# Edit the device name, friendly name and IP address (for manual IP)
# If you want to use DHCP, you will need to make more alterations to the wifi section
substitutions:
  devicename: ttgocam
  friendly_name: test esp32cam
  ip_address: 192.168.1.230
  
# sets up the device
esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit

# set up wifi
# CHANGE the gateway to suit your network
# NOTE I am using secrets for SSID and Password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  manual_ip:
    static_ip: $ip_address
    gateway: 192.168.1.1
    subnet: 255.255.255.0


# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA
ota:

# PIR motion sensor 
binary_sensor:
  - platform: gpio
    pin: GPIO33
    name: $friendly_name PIR
    device_class: motion

# Binary sensor for button - is named {friendly name} Button
  - platform: gpio
    pin:
      number: GPIO34
      mode: INPUT_PULLUP
      inverted: True
    name: $friendly_name Button

# board status sensor
  - platform: status
    name: $friendly_name Status

sensor:
# wifi signal sensor
  - platform: wifi_signal
    name: $friendly_name WiFi Signal
    update_interval: 10s
# uptime sensor
  - platform: uptime
    name: $friendly_name Uptime

# Camera
esp32_camera:
  name: $friendly_name Camera
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19
  power_down_pin: GPIO26
  resolution: 640x480
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false

# I2c for LCD
i2c:
  sda: GPIO21
  scl: GPIO22

# Fonts used for display (NOTE Files needed)
font:
  - file: "fonts/times-new-roman.ttf"
    id: tnr1
    size: 20
  - file: "fonts/times-new-roman.ttf"
    id: tnr2
    size: 35

# pull time from home assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# set up and display time and date on LCD
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.strftime(64, 0, id(tnr1), TextAlign::TOP_CENTER,"%d-%m-%Y", id(homeassistant_time).now());
      it.strftime(64, 64, id(tnr2), TextAlign::BASELINE_CENTER, "%H:%M", id(homeassistant_time).now());
